export const CUSTOMER_ADD_REQUEST = 'CUSTOMER_ADD_REQUEST';
export const CUSTOMER_ADD_SUCCESS = 'CUSTOMER_ADD_SUCCESS';
export const CUSTOMER_ADD_FAIL = 'CUSTOMER_ADD_FAIL';

export const CUSTOMER_DELETE_REQUEST = 'CUSTOMER_DELETE_REQUEST';
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS';
export const CUSTOMER_DELETE_FAIL = 'CUSTOMER_DELETE_FAIL';
